---
title: "QC_Colon_dm_Data"
author: "Alos Diallo"
date: "3/6/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
.libPaths("/dartfs-hpc/rc/lab/V/VaickusL/anaconda_installation/envs/R2/lib/R/library")
```

```{r message=FALSE, warning=FALSE}
library(minfi)
library(sesame)
library(pheatmap)
library(minfiData)
library(IlluminaHumanMethylationEPICmanifest)
library(FlowSorted.Blood.EPIC)
library(HiTIMED)
library(ggplot2)
library(dplyr)
library(IlluminaHumanMethylationEPICv2manifest)
library(IlluminaHumanMethylationEPICv2anno.20a1.hg38)
library(ExperimentHub)
sesameDataCache()
```

```{r, echo=FALSE}
load("/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Students/users/alos/colon_work/dm_data/no_match/idats/DH_Colon_HiTIMED.RDATA")
DHColon_HTD <- DHColon_HTD[,colSums(DHColon_HTD)>0]

covar.data <- read.csv("/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Students/users/alos/colon_work/dm_data/no_match/idats/Colon_DH_manifest.csv")
covar.data$patient <- paste(covar.data$Sentrix_ID,covar.data$Sentrix_Position,sep="_")
rownames(covar.data) <- covar.data$patient
```


```{r}
idat <- "/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Students/users/alos/colon_work/dm_data/no_match/idats/"
betas = openSesame(idat, func = getBetas) 
```












